### PR TITLE
Crop to honor maxSize intent parameters

### PR DESCRIPTION
**Pull request by aldoreyes**
Hi, noticed that when I set a maxSize through `withMaxSize` method, on newer android API versions than 10 the crop function returns a cropped image but it's not returning a resized image to match the max size parameters. 

Also I've set the getIntent method available at runtime, useful when using the android-support-library and to avoid forwarding the `onActivityResult` result into the current fragment,  i.e. you can run the following from inside a `android.support.v4.app.Fragment` instance, and receive the result inside the same instance method `onActivityResult`, otherwise the result is returned to the parent activity not the fragment:

    startActivityForResult(new Crop(inUri)
                        .output(outUri)
                        .asSquare()
                        .withMaxSize(96, 96)
                        .getIntent(this.getActivity()) //public method
                        , Crop.REQUEST_CROP);

    Probably not the best solution for both problems, just wanted to dive into the code and make some temporary solutions, while the library is updated. 

Pretty cool work btw, thank you.

### CODE REVIEW

**Comment by jdamcd** [comment]
Looks pretty good. Can you remove the changes to `Crop` so it's mergeable?

**Comment by aldoreyes** [comment]
@jdamcd Ok reverted, are you planning on making the `Crop.getIntent` function public from another thread? It's really useful to be able get the result on the fragment calling `startActivityForResult`, if not I can redo these changes on my branch after you merge.

Thank you

**Comment by jdamcd** [comment]
@aldoreyes `getIntent()` is public on master now.

**Comment by jdamcd** [comment]
This became unmergeable again, but I did basically the same thing on master.

**Pull request closed without merging**
