### PR TITLE
Support Fragments from support-v4.

### PR DESCRIPTION
**Pull request by nostra13**
Support Fragments from support-v4.
Update versions of buildTools and support-v4.

### CODE REVIEW

**Comment by bagintz** [comment]
This would be helpful for me too, thanks nostra13!

**Comment by austynmahoney** [comment]
This is very useful. That said, it can be worked around by using `Crop#getIntent(Context context)` and calling `startActivityForResult()` in your support Fragment.

**Comment by ticofab** [comment]
Useful indeed. The workaround suggested by @austynmahoney won't work with the current build on gradle (0.9.10) as it seems to lag a little behind. The change was introduced by @jdamcd on Jan 9 but hasn't been pushed yet. Do you have any alternative to fork the project and link from my local repo? Thanks for your work!

**Comment by austynmahoney** [comment]
Sorry, yes I built latest and I am using that in my project.

**Comment by ticofab** [comment]
Thanks @austynmahoney . Do you know when you're going to push a new version to Maven, @jdamcd ? Thank you.

**Review by RaiyanRiyadh9 — COMMENTED** [review]
Thanks for you

**Pull request merged**
